services:
  # this is the AI service
  torrentai:
    build: .
    restart: unless-stopped
    ports:
      - 5100:5100
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - OLLAMA_MODEL=llama3.2 # ollama model to use
      - PORT=5100 # port to open for web-ui
      # set some hosts for things defined in this file
      - PLEX_HOST=plex:32400
      - OLLAMA_HOST=ollama:11434
      - BITMAGNET_HOST=bitmagnet:3333
      - QTORRENT_HOST=torrent:8080

  # this downloads torrents
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env} 
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG}/torrent:/config
      - ${ROOT}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
  
  # this manages media, included GPU for transcoding
  plex:
    image: lscr.io/linuxserver/plex:latest
    runtime: nvidia
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PLEX_CLAIM=${PLEX_CLAIM} # your user-code, in .env
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
    volumes:
      - ${CONFIG}/plex/db:/config # plex database
      - ${ROOT}/transcode:/transcode # temp transcoded files
      - ${ROOT}:/media # media library
    deploy:
      resources:
        reservations:
          devices:
            - count: 1
              driver: nvidia
              capabilities: [gpu]

  # self-hosted AI
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    restart: unless-stopped
    volumes:
      - ${CONFIG}/ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - count: 1
              driver: nvidia
              capabilities: [gpu]

  # personal torrent search-engine
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet
    ports:
      - "3333:3333"
      - "3334:3334/tcp"
      - "3334:3334/udp"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - CLASSIFIER_DELETE_XXX=true # this makes it so it doesn't index files idententified as XXX
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy
  
  # needed for bitmagnet
  postgres:
    image: postgres:16-alpine
    volumes:
      - ${CONFIG}/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s